### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by khanon** [milo2012/metasploitHelper#20]
Hey there,
Followed instruction for a vanilla kali, here is the output:
```
root@kali:~/gits/metasploitHelper# python msfHelper.py 192.168.1.67 -i -a
[*] Launching Metasploit msfrpcd
[*] MSGRPC starting on 127.0.0.1:55552 (NO SSL):Msg...
[*] URI: /api/
[*] MSGRPC backgrounding at 2017-06-27 11:57:50 -0400...
[*] Reading from msfHelper.db
Traceback (most recent call last):
  File "msfHelper.py", line 2106, in <module>
    readDB()
  File "msfHelper.py", line 1905, in readDB
    if int(portNo)>int(greatthanPorts):
ValueError: invalid literal for int() with base 10: ''
```

```
root@kali:~/gits/metasploitHelper# ping 192.168.1.67
PING 192.168.1.67 (192.168.1.67) 56(84) bytes of data.
64 bytes from 192.168.1.67: icmp_seq=1 ttl=64 time=0.295 ms
```

**Comment by milo2012** [comment]
Hi, please do a git pull to update the files.  Sorry, I have accidentally introduced a bug with the new option I have added.  
The source code has been updated.  It should work now.
https://github.com/milo2012/metasploitHelper/commit/88ff24fa57364871c01e612b5423911e535a446a

**Comment by khanon** [comment]
Works perfect. Many thanks 🙌

**Comment by milo2012** [comment]
You're welcome.
