### ISSUE TITLE
not run metasploitHelper1.py : error xml.etree.ElementTree.ParseError: no element found: line 8, column 0

### ISSUE THREAD

**Issue by umasolution** [milo2012/metasploitHelper#8]
Traceback (most recent call last):
  File "metasploitHelper1.py", line 678, in <module>
    parseNmap(options.nmapFile)
  File "metasploitHelper1.py", line 596, in parseNmap
    tree=ElementTree.parse(file)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1183, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 657, in parse
    self._root = parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1655, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 8, column 0
root@versa:/home/versa/metasploitHelper-master#

**Comment by milo2012** [comment]
Can you let me know the full command which you used ? Thanks
